### ISSUE TITLE
Endpoint JSON fails with Trusty + Python 3.4

### ISSUE THREAD

**Issue by stub42** [juju-solutions/charms.reactive#180]
charms.reactive endpoints is not working with the Python 3.4 json library.
It is attempting to access the json.JSONDecodeError symbol which does not exist with Python 3.4

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-dse-11/.venv/lib/python3.4/site-packages/charms/reactive/__init__.py", line 71, in main
    hookenv._run_atstart()
  File "/var/lib/juju/agents/unit-dse-11/.venv/lib/python3.4/site-packages/charmhelpers/core/hookenv.py", line 1112, in _run_atstart
    callback(*args, **kwargs)
  File "/var/lib/juju/agents/unit-dse-11/.venv/lib/python3.4/site-packages/charms/reactive/endpoints.py", line 131, in _startup
    endpoint._manage_flags()
  File "/var/lib/juju/agents/unit-dse-11/.venv/lib/python3.4/site-packages/charms/reactive/endpoints.py", line 226, in _manage_flags
    for key, value in unit.received.items():
  File "/var/lib/juju/agents/unit-dse-11/.venv/lib/python3.4/_collections_abc.py", line 498, in __iter__
    yield (key, self._mapping[key])
  File "/var/lib/juju/agents/unit-dse-11/.venv/lib/python3.4/site-packages/charms/reactive/endpoints.py", line 832, in __getitem__
    except json.JSONDecodeError:
AttributeError: 'module' object has no attribute 'JSONDecodeError'
```

**Comment by johnsca** [comment]
Fixed with #181
